name: Build Unity Package

on: 
  workflow_dispatch:

env:
  packageName: "dev.drsakuu.humr"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
      - name: Checkout
        uses: actions/checkout@v3
    
      - name: get version
        id: version
        uses: notiz-dev/github-action-json-property@7c8cf5cc36eb85d8d287a8086a39dac59628eb31
        with: 
            path: "package.json"
            prop_path: "version"
    
      - name: Set Environment Variables
        run: |
          echo "unityPackage=${{ env.packageName }}-${{ steps.version.outputs.prop }}.unitypackage" >> $GITHUB_ENV\
      
      - name: Make Package Folder
        run: |
          mkdir Packages
          mkdir Packages/${{ env.packageName }}
          ls | grep -v Packages | xargs mv -t Packages/${{ env.packageName }}
              
      - name: Track Package Meta Files
        run: find "Packages/${{ env.packageName }}/" -name \*.meta >> metaList

      - name: Create UnityPackage
        uses: pCYSl5EDgo/create-unitypackage@cfcd3cf0391a5ef1306342794866a9897c32af0b
        with:
          package-path: ${{ env.unityPackage }}
          include-files: metaList
          
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v7.0.1
        with:
          archive: false
          path: ${{ env.unityPackage }}
